repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      name: Add license for all Python files
      files: ^(atr|tests)/(.*\.py$|.*\.pyi)$
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - LICENSE-template.txt
        - --fuzzy-match-generates-todo
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  -   id: shellcheck
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.36.4
  hooks:
    - id: djlint
      files: "atr/templates/.*\\.html$"
      types_or: ['html']
      args:
        - --profile=jinja
        - --lint
    - id: djlint
      name: Format HTML templates
      files: "atr/templates/.*\\.html$"
      types_or: ['html']
      args:
        - --profile=jinja
        - --reformat
- repo: https://github.com/thibaudcolas/pre-commit-stylelint
  rev: v16.14.1
  hooks:
    - id: stylelint
      additional_dependencies: ['stylelint@16.14.1', 'stylelint-config-standard@37.0.0']
      files: "atr/static/css/.*\\.css$"
      exclude: "atr/static/css/bootstrap\\..*\\.css$|atr/static/css/fontawesome\\.all\\.min\\.css$|atr/static/css/normalize\\.css$|atr/static/css/mermaid\\.min\\.css$"
      types_or: ['css']
      args: ['--fix']
- repo: local
  hooks:
    - id: ruff
      name: Ruff Linter
      entry: ruff check --fix
      language: system
      types: [python]
    - id: ruff-format
      name: Ruff Formatter
      entry: ruff format --force-exclude
      language: system
      types: [python]
    - id: mypy
      name: Mypy Type Check
      entry: mypy
      language: system
      require_serial: true
      types: [python]
      exclude: "tests" # see https://github.com/pre-commit/pre-commit/issues/2967
      args:
        - --config-file=pyproject.toml
        - --scripts-are-modules
    - id: pyright
      name: Pyright Type Check
      entry: pyright
      language: system
      require_serial: true
      types: [python]
      exclude: "tests"
