repos:
- repo: local
  hooks:
    - id: ruff
      name: Ruff Linter
      entry: ruff check --fix
      language: system
      types: [python]
      exclude: ^node_modules/

    - id: ruff-format
      name: Ruff Formatter
      entry: ruff format --force-exclude
      language: system
      types: [python]
      exclude: ^node_modules/

    - id: pyright
      name: Pyright Type Check
      entry: pyright
      language: system
      require_serial: true
      types: [python]
      exclude: ^(node_modules|tests)/
