repos:
  - repo: local
    hooks:
      - id: black
        name: Black Code Formatter
        entry: black --line-length 120
        language: system
        types: [python]
        exclude: ^asfquart/

      - id: ruff
        name: Ruff Linter
        entry: ruff check --fix
        language: system
        types: [python]
        exclude: ^asfquart/

      - id: pyright
        name: Pyright Type Check
        entry: pyright
        language: system
        types: [python]
        exclude: ^asfquart/
