# TODO: Add a shellcheck lint
exclude: '^(asfquart)'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      name: Add license for all Python files
      files: ^atr/.*\.py$|^atr/.*\.pyi$
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - LICENSE-template.txt
        - --fuzzy-match-generates-todo
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.36.4
  hooks:
    - id: djlint
      files: "atr/templates/.*\\.html$"
      types_or: ['html']
      args:
        - --profile=jinja
        - --lint
    - id: djlint
      name: Format HTML templates
      files: "atr/templates/.*\\.html$"
      types_or: ['html']
      args:
        - --profile=jinja
        - --reformat
- repo: local
  hooks:
    - id: ruff
      name: Ruff Linter
      entry: ruff check --fix
      language: system
      types: [python]
    - id: ruff-format
      name: Ruff Formatter
      entry: ruff format --force-exclude
      language: system
      types: [python]
    - id: mypy
      name: Mypy Type Check
      entry: mypy
      language: system
      types: [python]
      args:
        - --config-file=pyproject.toml
    - id: pyright
      name: Pyright Type Check
      entry: pyright
      language: system
      types: [python]
