repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-toml
      exclude: ^node_modules/
    - id: check-yaml
      exclude: ^node_modules/
    - id: end-of-file-fixer
      exclude: ^node_modules/
    - id: mixed-line-ending
      exclude: ^node_modules/
    - id: trailing-whitespace
      exclude: ^node_modules/
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: insert-license
      name: Add license for all Python files
      files: ^(atr|scripts|tests)/(.*\.py$|.*\.pyi)$
      args:
        - --comment-style
        - "|#|"
        - --license-filepath
        - scripts/ci/LICENSE-template.txt
        - --fuzzy-match-generates-todo
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  -   id: shellcheck
- repo: https://github.com/Riverside-Healthcare/djLint
  rev: v1.36.4
  hooks:
    - id: djlint
      files: "atr/templates/.*\\.html$"
      types_or: ['html']
      args:
        - --profile=jinja
        - --lint
    - id: djlint
      name: Format HTML templates
      files: "atr/templates/.*\\.html$"
      types_or: ['html']
      args:
        - --profile=jinja
        - --reformat
- repo: https://github.com/thibaudcolas/pre-commit-stylelint
  rev: v16.14.1
  hooks:
    - id: stylelint
      additional_dependencies: ['stylelint@16.14.1', 'stylelint-config-standard@37.0.0']
      files: "atr/static/css/.*\\.css$"
      exclude: "atr/static/css/bootstrap\\..*\\.css$|atr/static/css/bootstrap\\-.*\\.css$|atr/static/css/normalize\\.css$|atr/static/css/mermaid\\.min\\.css$"
      types_or: ['css']
      args: ['--fix']
- repo: local
  hooks:
    - id: poetry-check
      name: poetry-check
      description: run poetry check to validate config
      entry: poetry check
      language: python
      pass_filenames: false
      files: ^(.*/)?(poetry\.lock|pyproject\.toml)$

    - id: ruff
      name: Ruff Linter
      entry: ruff check --fix
      language: system
      types: [python]
      exclude: ^node_modules/

    - id: ruff-format
      name: Ruff Formatter
      entry: ruff format --force-exclude
      language: system
      types: [python]
      exclude: ^node_modules/

    - id: pyright
      name: Pyright Type Check
      entry: pyright
      language: system
      require_serial: true
      types: [python]
      exclude: ^(node_modules|tests)/

    - id: jinja-route-check
      name: Jinja Route Checker
      description: Check whether routes used in Jinja2 templates actually exist
      entry: poetry run python scripts/lint/jinja_route_checker.py
      language: system
      pass_filenames: false
      always_run: true
