[project]
name = "tooling-atr-experiment"
version = "0.0.1"
description = "Some experiments with ATR"
authors = [
  { name = "ASF Tooling", email = "dev@tooling.apache.org" }
]
license = "Apache-2.0"
readme = "README.md"
requires-python = "~=3.13"
dependencies = [
  "alembic~=1.14",
  "asfquart",
  "cryptography~=44.0",
  "httpx~=0.27",
  "hypercorn~=0.17",
  "python-gnupg~=0.5",
  "sqlmodel~=0.0",
]

[dependency-groups]
dev = [
  "djlint>=1.36.4",
  "mypy>=1.15.0",
  "pre-commit>=2.20.0",
  "pyright>=1.1.393",
  "ruff>=0.9.4",
]

# Other configuration

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
djlint = "^1.36.4"
mypy = "^1.15.0"
pre-commit = ">=2.20.0"
pyright = ">=1.1.393"
ruff = ">=0.9.4"

[tool.poetry.group.main.dependencies]
alembic = "~=1.14"
asfquart = { path = "./asfquart", develop = true }
cryptography = "~=44.0"
httpx = "~=0.27"
hypercorn = "~=0.17"
python-gnupg = "~=0.5"
sqlmodel = "~=0.0"

[tool.pyright]
include = ["atr"]
exclude = ["**/node_modules", "**/__pycache__", ".venv*", "asfquart"]
ignore = []
defineConstant = { DEBUG = true }
stubPath = "typestubs"
reportMissingImports = "error"
reportMissingTypeStubs = false
pythonVersion = "3.13"
executionEnvironments = [
  { root = ".", pythonVersion = "3.13" }
]

[tool.ruff]
lint.select = ["E", "W", "F", "C90"]
lint.ignore = []
line-length = 120
exclude = ["asfquart"]

[tool.uv.sources]
asfquart = { path = "./asfquart", editable = true }

[tool.mypy]
python_version = "3.13"
exclude = ["asfquart"]
mypy_path = "typestubs"
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
# warn_unreachable = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "asfquart.*"
ignore_errors = true

[tool.djlint]
profile = "jinja"
extension = "html"
indent = 2
blank_line_after_tag = "load,extends,include,html"
close_void_tags = true
format_css = true
format_js = true
max_line_length = 120
use_gitignore = true
preserve_blank_lines = true
ignore = "H006,H031"
include = "atr/templates"
